//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS_Textil.IPInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPInfo.MIscServicesSoap")]
    public interface MIscServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIPAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetIPAdd(string sClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInstanceNM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetInstanceNM(string sClientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPortNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPortNo(string sClientID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MIscServicesSoapChannel : CIS_Textil.IPInfo.MIscServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MIscServicesSoapClient : System.ServiceModel.ClientBase<CIS_Textil.IPInfo.MIscServicesSoap>, CIS_Textil.IPInfo.MIscServicesSoap {
        
        public MIscServicesSoapClient() {
        }
        
        public MIscServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MIscServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MIscServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MIscServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetIPAdd(string sClientID) {
            return base.Channel.GetIPAdd(sClientID);
        }
        
        public string GetInstanceNM(string sClientID) {
            return base.Channel.GetInstanceNM(sClientID);
        }
        
        public string GetPortNo(string sClientID) {
            return base.Channel.GetPortNo(sClientID);
        }
    }
}
